### ISSUE TITLE
crash when autothread tries to make a thread on a deleted message from media only channel

### ISSUE THREAD

**Issue by DjMuffinTops** [DjMuffinTops/DJMTbot#66]
sending a non-media msg gets deleted, and then auto thread does this
![image](https://user-images.githubusercontent.com/68816695/153136474-f43c8136-1fb6-49ab-935c-bb8b354f4b38.png)

probably need to change the order of operations and make deletes happen after thread creation

**Comment by reveriadive** [comment]
Threads created still exist after the deletion of the original message. Changing the order could be nefarious to those that know this.

**Comment by DjMuffinTops** [comment]
resolved in 
- #67 
- #73
